import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const links = [
  { href: '/', label: 'Home' },
  { href: '/todos', label: 'Todos' },
  { href: '/docs', label: 'Docs' },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav>
            <ul className='flex items-center m-4'>
              {links.map(({ href, label }) => (
                <li key={href} className='border-solid border-2 border-sky-500 w-32 p-4 text-center'>
                  <Link href={href}>
                    <p>{label}</p>
                  </Link>
                </li>
              ))}
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
